spring:
  #thymeleaf ??
  thymeleaf:
    #????
    cache: false
  #MySQL??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characherEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    #Linux
#    password: Zy981022.
    #本地
    password: Zy981022
    hikari:
      #?????
      pool-name: DateHikariCP
      #???????
      minimum-idle: 5
      #?????????????600000(10???
      idle-timeout: 1800000
      #?????
      maximum-pool-size: 10
      auto-commit: true
      #?????????0???????180000?30???
      max-lifetime: 1800000
      #?????????30?
      connection-timeout: 30000
      #????????????
      connection-test-query: SELECT 1
  #redis conf
  redis:
    host: 124.223.197.115
#    host: localhost
    port: 6376
    database: 0
    password: zy981022.
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
#mybatis-plus??
mybatis-plus:
  #??Mapper.xml????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #??Mybatis????????(????????
  type-aliases-package: com.shnu.seckill.pojo
#Mybatis SQL??????????????Mapper.xml?????
logging:
  level:
    com.shnu.seckill.mapper: debug
