spring:
  #thymeleaf ??
  thymeleaf:
    #????
    cache: false
  #MySQL??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characherEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    #Linux
#    password: Zy981022.
    #本地
    password: Zy981022
    hikari:
      #?????
      pool-name: DateHikariCP
      #???????
      minimum-idle: 5
      #?????????????600000(10???
      idle-timeout: 1800000
      #?????
      maximum-pool-size: 10
      auto-commit: true
      #?????????0???????180000?30???
      max-lifetime: 1800000
      #?????????30?
      connection-timeout: 30000
      #????????????
      connection-test-query: SELECT 1
  #redis conf
  redis:
    host: 124.223.197.115
#    host: localhost
    port: 6376
    database: 0
    password: zy981022.
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        #最小空闲连接
        min-idle: 5
  #静态资源处理
  web:
    resources:
      #启动默认静态资源处理，默认启动
      add-mappings: true
      cache:
        cachecontrol:
          #缓存相应时间，单位秒
          max-age: 3600
      chain:
        #资源链自动缓存，默认启动
        cache: true
        #启动资源
        enabled: true
        # 启用压缩资源
        compressed: true
      static-locations: classpath:/static/
#        #启用h5应用缓存
#        html-aaplication-cache: true

  #RabbitMQ
  rabbitmq:
    host: 124.223.197.115
#    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息
        prefetch: 1
        #启动时是否默认自动容器
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
      #发布重试，默认false
        enabled: true
      #重试时间
        initial-interval: 1000ms
        #重试最大次数
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数，
        multiplier: 1

#mybatis-plus??
mybatis-plus:
  #??Mapper.xml????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #??Mybatis????????(????????
  type-aliases-package: com.shnu.seckill.pojo
#Mybatis SQL??????????????Mapper.xml?????
logging:
  level:
    com.shnu.seckill.mapper: debug
